# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: O Amendoim
author: Matheus Avellar
email: o@amendo.im
description: >-
  Blog
footer-desc: >-
  Não sei sobre o que é esse blog mas, enfim, ele existe.
# Subpath of the site, e.g. /blog
baseurl: ""
# Base hostname & protocol for the site, e.g. http://example.com
url: "https://o.amendo.im/"
# Default for organizing URLs
# e.g. 2010/08/15/new-post
permalink: /:year/:month/:day/:title
show_excerpts: true
excerpt_separator: "<!-- more -->"

twitter_username: aveIIar
github_username:  MatheusAvellar

# Build settings
markdown: kramdown
# Disable "smart" quotes
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - _headers

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .jekyll-cache
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
